#!/usr/bin/env bash
set -euo pipefail
root=$(cd "$(dirname "$0")/.." && pwd)

grep -qx 'GLM_RECIPE_COMMIT=1576746a04983b6eded0551dbf22512ee9e95654' "$root/UPSTREAM.lock"
grep -qx 'GLM_RECIPE_TARGET_VERSION=v1.5' "$root/UPSTREAM.lock"
grep -qx 'GLM_RECIPE_TARGET_COMMIT=1576746a04983b6eded0551dbf22512ee9e95654' "$root/UPSTREAM.lock"
grep -qx 'GLM_RECIPE_TARGET_TREE=29ab0f1f9eb994d719f4bb47070cd854dc9f4c8b' "$root/UPSTREAM.lock"
grep -qx 'GLM_RECIPE_TARGET_TENSORFOLD_VERSION=0.6.0' "$root/UPSTREAM.lock"
grep -qx 'GLM_RECIPE_TARGET_IMAGE_REPO_DIGEST=sha256:ef83797d791fef96c4605e8d37367aca6de5aeac7bb672792cb682e2e55d4237' "$root/UPSTREAM.lock"
grep -qx 'TENSORFOLD_IMAGE_NAME=tensorfold-glm53:v0.6.0' "$root/UPSTREAM.lock"
grep -qx 'TENSORFOLD_IMAGE_ID=sha256:e97db95dd4b3f9a5ebd6ddeafb8d7d422dda729cc01b33d7f5c6ecfcf9cf2aaf' "$root/UPSTREAM.lock"
grep -qx 'TENSORFOLD_IMAGE_REPO_DIGEST=sha256:ef83797d791fef96c4605e8d37367aca6de5aeac7bb672792cb682e2e55d4237' "$root/UPSTREAM.lock"
grep -qx 'TENSORFOLD_LIVE_PACKAGE_VERSION=0.6.0' "$root/UPSTREAM.lock"
grep -qx 'TENSORFOLD_PATCHES=9f73cca659a1' "$root/UPSTREAM.lock"
grep -qx 'TENSORFOLD_LATEST_RELEASE=0.6.5' "$root/UPSTREAM.lock"
grep -qx 'TENSORFOLD_LATEST_RELEASE_COMMIT=609ca419abecebdc5a059498a613680bd3aa847f' "$root/UPSTREAM.lock"
grep -qx 'TENSORFOLD_MAC_PACKAGE_VERSION=0.6.5' "$root/UPSTREAM.lock"
grep -qx 'TENSORFOLD_MAC_SOURCE_COMMIT=609ca419abecebdc5a059498a613680bd3aa847f' "$root/UPSTREAM.lock"
grep -qx 'TENSORFOLD_MAC_PATCHED_TREE_SHA256=58147488b2f9ba740e9ece1de9fb51d002bfbfeb47f348c5fee3a220b98ee251' "$root/UPSTREAM.lock"
grep -qx 'GLM_MODEL_REVISION=9eaebb7c4e96d983dcd538e18624622ba5b820a8' "$root/UPSTREAM.lock"
grep -qx 'MCDMA_COMMIT=e672c14ff9fc7b38994caf73025cf1588b4de74e' "$root/UPSTREAM.lock"
grep -qx 'THREE_MACHINE_HANDOFF_CHUNK_MIB=64' "$root/config.example.env"
grep -qx 'THREE_MACHINE_MCDMA_REPLY_MIB=64' "$root/config.example.env"
grep -q 'DRAFTER=mtp' "$root/scripts/start.sh"
grep -qx 'THREE_MACHINE_METAL_LINEAR_SHA256=replace-with-verified-patched-linear-py-sha256' "$root/config.example.env"
grep -qx 'THREE_MACHINE_METAL_WEIGHTS_SHA256=replace-with-verified-patched-weights-py-sha256' "$root/config.example.env"
grep -qx 'THREE_MACHINE_STAGE_MANIFEST_SHA256=replace-with-verified-stage-content-manifest-sha256' "$root/config.example.env"
grep -qx 'THREE_MACHINE_PROJECT_DIR=/home/user/.local/share/glm53-three-machine/runtime' "$root/config.example.env"
grep -qx 'THREE_MACHINE_STUDIO_DIR=/Users/user/.local/share/glm53-three-machine/runtime' "$root/config.example.env"
grep -qx 'THREE_MACHINE_MTP_DRAFTS=3' "$root/config.example.env"
grep -qx 'THREE_MACHINE_MTP_CONFIDENCE=0.35' "$root/config.example.env"
grep -qx 'THREE_MACHINE_MCDMA_PULL=1' "$root/config.example.env"
grep -qx 'THREE_MACHINE_KDA_CHUNKED=1' "$root/config.example.env"
! grep -q -- '--mtp-confidence' "$root/scripts/start-native-portable.sh"
grep -q -- '-e TF_GLM_KV=bf16' "$root/scripts/start-cache-handoff.sh"
grep -q -- 'kda_chunked=$THREE_MACHINE_KDA_CHUNKED' "$root/scripts/start-cache-handoff.sh"
grep -q -- 'prefill_module=experiments.three_machine.cuda_bf16_qk' "$root/scripts/start-cache-handoff.sh"
grep -q -- 'prefill_module=experiments.three_machine.cuda_mac_kda' "$root/scripts/start-cache-handoff.sh"
grep -q -- 'prefill_module=experiments.three_machine.cuda_metal_qmm' "$root/scripts/start-cache-handoff.sh"
grep -q -- 'prefill_module=experiments.three_machine.cuda_torch_qmm' "$root/scripts/start-cache-handoff.sh"
grep -q -- 'prefill_module=experiments.three_machine.cuda_scalar_qmm' "$root/scripts/start-cache-handoff.sh"
grep -q -- 'prefill_module=experiments.three_machine.cuda_float32_qmm' "$root/scripts/start-cache-handoff.sh"
grep -q -- 'prefill_module=experiments.three_machine.cuda_float32_mac_kda' "$root/scripts/start-cache-handoff.sh"
grep -q -- 'prefill_module=experiments.three_machine.cuda_float32_mac_sigmoid' "$root/scripts/start-cache-handoff.sh"
awk '
  /if \[\[ "\$float32_qmm_layer0" == true \]\]/ { inside=1; next }
  inside && /kda_chunked=0/ { found=1 }
  inside && /^fi$/ { exit }
  END { exit !found }
' "$root/scripts/start-cache-handoff.sh"
grep -q -- 'kda_chunked=0' "$root/scripts/start-cache-handoff.sh"
grep -q -- '--bf16-qk' "$root/scripts/start-cache-handoff.sh"
grep -q -- '--mac-kda' "$root/scripts/start-cache-handoff.sh"
grep -q -- '--metal-qmm' "$root/scripts/start-cache-handoff.sh"
grep -q -- '--torch-qmm-layer0' "$root/scripts/start-cache-handoff.sh"
grep -q -- '--scalar-qmm-layer0' "$root/scripts/start-cache-handoff.sh"
grep -q -- '--float32-qmm-layer0' "$root/scripts/start-cache-handoff.sh"
grep -q -- '--float32-mac-kda-layer0' "$root/scripts/start-cache-handoff.sh"
grep -q -- '--float32-mac-sigmoid-layer0' "$root/scripts/start-cache-handoff.sh"
grep -q -- '--kda-trace-layer' "$root/scripts/start-cache-handoff.sh"
! grep -q -- '-e TF_GLM_KV=fp8' "$root/scripts/start-cache-handoff.sh"
grep -q 'head_fact_pid=\$!' "$root/scripts/preflight-cache-handoff.sh"
grep -q 'worker_fact_pid=\$!' "$root/scripts/preflight-cache-handoff.sh"
grep -q 'studio_fact_pid=\$!' "$root/scripts/preflight-cache-handoff.sh"
grep -q 'exec .*chat-three-machine.sh' "$root/scripts/run-three-machine.sh"
! grep -q 'experiments/three_machine/mac_stage.py' "$root/scripts/run-three-machine.sh"
grep -q 'mcdma_transport_healthy "$link"' "$root/scripts/start-cache-replay.sh"
grep -q -- '--network=host --ipc=host' "$root/scripts/start-cache-replay.sh"
grep -q 'mcdma_transport_healthy "$link"' "$root/scripts/start-cache-handoff.sh"
grep -q 'get("service") == "poll"' "$root/scripts/lib.sh"
! grep -Eq 'local .*timeout=.*deadline=.*timeout|local .*phase=.*tag=.*phase' \
  "$root/scripts/benchmark-concurrent-capacity.sh"
python3 "$root/scripts/check-public-release.py"
printf 'PASS: pinned inputs and private-data guard\n'
